version: "3.3"
services:
  db:
    container_name: myreal-postgres-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: eatsleepcode
      POSTGRES_USER: dbuser
      POSTGRES_DB: myreal-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myreal-node-app
    image: myreal-backend
    depends_on:
      - db
    ports:
      - "4192:4192"
